# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Site Info
# =========

title: UDL docs
tagline: User Defined Language for Notepad++
description: This site serves to demonstrate and document new UDL 2.1. UDL stands for User Defined Language, it is a feature of Notepad++ editor through which users can define their own syntax highlighting.
original_site_url: https://ivan-radic.github.io/udl-documentation
author: Ivan Radić
author_id: ivan-radic
author_url: https://github.com/ivan-radic
# note: do not change author info, unless ownership of original repo is changed

# Dev Env
# =======

repository: ivan-radic/udl-documentation # required by github-pages gem
baseurl: /udl-documentation # for hosting in Github Pages
host: 0.0.0.0
exclude:
  - CONTRIBUTING.md
  - README.md
  - coffeelint.json
  # includes the list by Jekyll defaults:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  # note: dotfiles are excluded by default

# Build Settings
# ==============

theme: minima
npp_ui_green: "#ADCC6E"
markdown: kramdown
show_downloads: false
# plugins:
#   - jekyll-feed

# Information from Official Doc
# =============================

# https://help.github.com/en/github/working-with-github-pages/about-github-pages-and-jekyll#plugins

# GitHub Pages uses plugins that are enabled by default and cannot be disabled:

#   - jekyll-coffeescript
#   - jekyll-default-layout
#   - jekyll-gist
#   - jekyll-github-metadata
#   - jekyll-optional-front-matter
#   - jekyll-paginate
#   - jekyll-readme-index
#   - jekyll-titles-from-headings
#   - jekyll-relative-links

# Here are some notable gems.
# To enable an optional plugin, you must add it to your _config.yml file.

# plugins:
#   - jekyll-feed
#   - jekyll-redirect-from
#   - jekyll-seo-tag
#   - jekyll-sitemap
#   - jekyll-avatar
#   - jemoji
#   - jekyll-mentions
